SHELL := /bin/bash

ROOT := $(CURDIR)
BUILD := $(ROOT)/build
LINUX := $(ROOT)/vendor/linux
LINUX_BUILD := $(BUILD)/linux
EROFS_UTILS := $(ROOT)/vendor/erofs-utils
EROFS_UTILS_BUILD := $(BUILD)/erofs-utils

ARCH ?= x86_64
JOBS ?= $(shell nproc)
QEMU ?= qemu-system-x86_64
QEMU_ACCEL ?= tcg

KERNEL_IMAGE := $(LINUX_BUILD)/arch/x86/boot/bzImage
ROOTFS_DIR := $(BUILD)/rootfs
INIT_C := $(BUILD)/rootfs-init.c
INIT_BIN := $(ROOTFS_DIR)/init
INITRAMFS := $(BUILD)/initramfs.cpio.gz
EROFS_SRC := $(BUILD)/erofs-root
EROFS_IMG := $(BUILD)/rootfs.erofs
MKFS_EROFS := $(EROFS_UTILS_BUILD)/mkfs/mkfs.erofs
SAMPLE ?= $(EROFS_IMG)
EROFS_DRIVE = -drive file=$(abspath $(SAMPLE)),if=virtio,format=raw,readonly=on

KERNEL_CMDLINE := console=ttyS0 earlyprintk=serial panic=-1
QEMU_ARGS := \
	-machine accel=$(QEMU_ACCEL) \
	-cpu max \
	-m 1024M \
	-smp 2 \
	-nographic \
	-no-reboot \
	-kernel $(KERNEL_IMAGE) \
	-initrd $(INITRAMFS) \
	-append "$(KERNEL_CMDLINE)"

.PHONY: all apt-deps deps-check kernel-config kernel erofs-utils initramfs erofs-image run smoke oracle clean distclean help

all: kernel initramfs erofs-image

help:
	@printf '%s\n' \
		'Targets:' \
		'  make apt-deps       Install required Ubuntu/Debian packages' \
		'  make deps-check     Check host tools needed for the boot environment' \
		'  make kernel-config  Generate an x86_64 config with EROFS built in' \
		'  make kernel         Build vendor/linux bzImage' \
		'  make erofs-utils    Build vendor/erofs-utils mkfs.erofs' \
		'  make initramfs      Build the minimal EROFS-mounting initramfs' \
		'  make erofs-image    Build build/rootfs.erofs' \
		'  make run            Build everything and boot vendor Linux in QEMU' \
		'  make smoke          Boot with a timeout and verify mount plus traversal' \
		'  make oracle SAMPLE=x Boot an arbitrary read-only EROFS sample' \
		'  make clean          Remove generated build artifacts'

apt-deps:
	sudo apt update
	sudo apt install -y build-essential flex bison bc libssl-dev cpio gzip rsync \
		autoconf automake libtool libtool-bin pkg-config qemu-system-x86 \
		dwarves libelf-dev liblz4-tool zstd uuid-dev liblz4-dev liblzma-dev zlib1g-dev libzstd-dev

deps-check:
	@missing=(); \
	for tool in gcc make flex bison bc openssl cpio gzip rsync autoconf automake libtoolize pkg-config $(QEMU); do \
		command -v $$tool >/dev/null 2>&1 || missing+=($$tool); \
	done; \
	if (($${#missing[@]})); then \
		echo "Missing required tools: $${missing[*]}"; \
		echo "Install them with: make apt-deps"; \
		exit 1; \
	fi

kernel-config: deps-check
	@if [ -f "$(LINUX)/.config" ] || [ -d "$(LINUX)/include/config" ]; then \
		echo "Cleaning previous in-tree kernel build..."; \
		$(MAKE) -C $(LINUX) ARCH=$(ARCH) mrproper; \
	fi
	@mkdir -p $(LINUX_BUILD)
	$(MAKE) -C $(LINUX) O=$(LINUX_BUILD) ARCH=$(ARCH) x86_64_defconfig
	$(ROOT)/scripts/enable-erofs-config.sh $(LINUX) $(LINUX_BUILD)

kernel: kernel-config
	$(MAKE) -C $(LINUX) O=$(LINUX_BUILD) ARCH=$(ARCH) -j$(JOBS) bzImage

erofs-utils: deps-check
	@if [ ! -x "$(MKFS_EROFS)" ]; then \
		if [ -f "$(EROFS_UTILS)/Makefile" ]; then \
			echo "Cleaning previous in-tree erofs-utils build..."; \
			$(MAKE) -C $(EROFS_UTILS) distclean 2>/dev/null || true; \
		fi; \
		cd $(EROFS_UTILS) && ./autogen.sh; \
		mkdir -p $(EROFS_UTILS_BUILD); \
		cd $(EROFS_UTILS_BUILD) && $(EROFS_UTILS)/configure --disable-fuse && $(MAKE) -j$(JOBS); \
	fi

$(INIT_C): scripts/rootfs-init.c
	@mkdir -p $(BUILD)
	cp $< $@

$(INIT_BIN): $(INIT_C)
	@rm -rf $(ROOTFS_DIR)
	@mkdir -p $(ROOTFS_DIR)/{dev,proc,sys,mnt/erofs,tmp}
	gcc -static -Os -Wall -Wextra -o $@ $<

initramfs: $(INIT_BIN)
	cd $(ROOTFS_DIR) && find . -print0 | cpio --null -ov --format=newc | gzip -9 > $(INITRAMFS)

erofs-image: erofs-utils
	@rm -rf $(EROFS_SRC)
	@mkdir -p $(EROFS_SRC)/etc $(EROFS_SRC)/demo
	printf 'hello from an EROFS-backed QEMU guest\n' > $(EROFS_SRC)/demo/hello.txt
	printf 'This read-only filesystem was generated by make erofs-image.\n' > $(EROFS_SRC)/etc/issue
	$(MKFS_EROFS) $(EROFS_IMG) $(EROFS_SRC)

run: all
	$(QEMU) $(QEMU_ARGS) $(EROFS_DRIVE)

oracle: kernel initramfs
	@test -f "$(SAMPLE)" || { echo "Sample not found: $(SAMPLE)"; exit 1; }
	@mkdir -p $(BUILD)
	@set -o pipefail; \
	source scripts/kernel-replay-common.sh; \
	timeout 80s $(QEMU) $(QEMU_ARGS) $(EROFS_DRIVE) 2>&1 | tee $(BUILD)/qemu-oracle.log || rc=$$?; \
	qemu_rc="$${rc:-0}"; \
	if [ "$$qemu_rc" != 0 ] && [ "$$qemu_rc" != 124 ]; then exit "$$qemu_rc"; fi; \
	classify_dmesg "$(BUILD)/qemu-oracle.log" "$$qemu_rc"; \
	echo "$$REPLAY_RESULT: $$REPLAY_MSG"; \
	if [ "$$REPLAY_RESULT" != "ACCEPTED" ] && [ "$$REPLAY_RESULT" != "REJECTED" ]; then exit 1; fi

smoke: all
	@mkdir -p $(BUILD)
	@set -o pipefail; \
	source scripts/kernel-replay-common.sh; \
	timeout 80s $(QEMU) $(QEMU_ARGS) $(EROFS_DRIVE) 2>&1 | tee $(BUILD)/qemu-smoke.log || rc=$$?; \
	qemu_rc="$${rc:-0}"; \
	if [ "$$qemu_rc" != 0 ] && [ "$$qemu_rc" != 124 ]; then exit "$$qemu_rc"; fi; \
	classify_dmesg "$(BUILD)/qemu-smoke.log" "$$qemu_rc"; \
	echo "$$REPLAY_RESULT: $$REPLAY_MSG"; \
	if [ "$$REPLAY_RESULT" != "ACCEPTED" ]; then exit 1; fi

clean:
	rm -rf $(BUILD)

distclean: clean
	$(MAKE) -C $(LINUX) ARCH=$(ARCH) mrproper 2>/dev/null || true
	@if [ -f "$(EROFS_UTILS)/Makefile" ]; then $(MAKE) -C $(EROFS_UTILS) distclean 2>/dev/null || true; fi
