[package]
name = "erofs-rs"
version = "0.2.1"
edition = "2024"
authors = ["Dreamacro"]
description = "A pure Rust library for reading and creating EROFS (Enhanced Read-Only File System) images"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Dreamacro/erofs-rs"
keywords = ["erofs", "filesystem", "readonly", "linux"]
categories = ["filesystem"]
readme = "../README.md"
rust-version = "1.89"

[lints]
workspace = true

[features]
default = ["std"]
std = []
opendal = ["dep:opendal"]

[dependencies]
binrw = { workspace = true, default-features = true }
bitflags = { workspace = true }
bytes = { workspace = true, default-features = true }
erofs-format = { version = "0.1.0", path = "../erofs-format" }
memmap2 = { workspace = true, default-features = true }
opendal = { workspace = true, optional = true }
rustix = { workspace = true, features = ["fs", "std"] }
thiserror = { workspace = true, default-features = true }
typed-path = { workspace = true, default-features = true }
