[package]
name = "erofs-lab"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
erofs-format = { path = "../erofs-format" }
rustix = { workspace = true, default-features = true, features = ["fs"] }
erofs-rs = { path = "../erofs" }
rand_chacha = { workspace = true, default-features = true }
rand_core = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true, features = ["derive"] }
serde_json = { workspace = true, default-features = true }
sha2 = { workspace = true, default-features = true }
thiserror = { workspace = true, default-features = true }
